package shared

case class Country(id: String, label: String)

object Catalog {
  val Countries: Seq[Country] = Seq(
    Country(id = "JPN", label = "Japan"),
    Country(id = "IND", label = "India"),
    Country(id = "VNM", label = "Vietnam"),
    Country(id = "IDN", label = "Indonesia"),
    Country(id = "MYS", label = "Malaysia"),
    Country(id = "PHL", label = "Philippines"),
    Country(id = "HKG", label = "Hong Kong"),
    Country(id = "SGP", label = "Singapore"),
    Country(id = "AUS", label = "Australia"),
    Country(id = "CHN", label = "China"),
    Country(id = "AFG", label = "Afghanistan"),
    Country(id = "ALB", label = "Albania"),
    Country(id = "DZA", label = "Algeria"),
    Country(id = "ASM", label = "American Samoa"),
    Country(id = "AND", label = "Andorra"),
    Country(id = "AGO", label = "Angola"),
    Country(id = "AIA", label = "Anguilla"),
    Country(id = "ATA", label = "Antarctica"),
    Country(id = "ATG", label = "Antigua and Barbuda"),
    Country(id = "ARG", label = "Argentina"),
    Country(id = "ARM", label = "Armenia"),
    Country(id = "ABW", label = "Aruba"),
    Country(id = "AUT", label = "Austria"),
    Country(id = "AZE", label = "Azerbaijan"),
    Country(id = "BHS", label = "Bahamas"),
    Country(id = "BHR", label = "Bahrain"),
    Country(id = "BGD", label = "Bangladesh"),
    Country(id = "BRB", label = "Barbados"),
    Country(id = "BLR", label = "Belarus"),
    Country(id = "BEL", label = "Belgium"),
    Country(id = "BLZ", label = "Belize"),
    Country(id = "BEN", label = "Benin"),
    Country(id = "BMU", label = "Bermuda"),
    Country(id = "BTN", label = "Bhutan"),
    Country(id = "BOL", label = "Bolivia (Plurinational State of)"),
    Country(id = "BES", label = "Bonaire (Saint Eustatius and Saba)"),
    Country(id = "BIH", label = "Bosnia and Herzegovina"),
    Country(id = "BWA", label = "Botswana"),
    Country(id = "BVT", label = "Bouvet Island"),
    Country(id = "BRA", label = "Brazil"),
    Country(id = "IOT", label = "British Indian Ocean Territory"),
    Country(id = "BRN", label = "Brunei Darussalam"),
    Country(id = "BGR", label = "Bulgaria"),
    Country(id = "BFA", label = "Burkina Faso"),
    Country(id = "BDI", label = "Burundi"),
    Country(id = "KHM", label = "Cambodia"),
    Country(id = "CMR", label = "Cameroon"),
    Country(id = "CAN", label = "Canada"),
    Country(id = "CPV", label = "Cape Verde"),
    Country(id = "CYM", label = "Cayman Islands"),
    Country(id = "CAF", label = "Central African Republic"),
    Country(id = "TCD", label = "Chad"),
    Country(id = "CHL", label = "Chile"),
    Country(id = "CXR", label = "Christmas Island"),
    Country(id = "CCK", label = "Cocos (Keeling) Islands"),
    Country(id = "COL", label = "Colombia"),
    Country(id = "COM", label = "Comoros"),
    Country(id = "COG", label = "Congo"),
    Country(id = "COD", label = "Congo (The Democratic Republic of the)"),
    Country(id = "COK", label = "Cook Islands"),
    Country(id = "CRI", label = "Costa Rica"),
    Country(id = "HRV", label = "Croatia"),
    Country(id = "CUB", label = "Cuba"),
    Country(id = "CUW", label = "Curacao"),
    Country(id = "CYP", label = "Cyprus"),
    Country(id = "CZE", label = "Czech Republic"),
    Country(id = "CIV", label = "Cote d'Ivoire"),
    Country(id = "DNK", label = "Denmark"),
    Country(id = "DJI", label = "Djibouti"),
    Country(id = "DMA", label = "Dominica"),
    Country(id = "DOM", label = "Dominican Republic"),
    Country(id = "ECU", label = "Ecuador"),
    Country(id = "EGY", label = "Egypt"),
    Country(id = "SLV", label = "El Salvador"),
    Country(id = "GNQ", label = "Equatorial Guinea"),
    Country(id = "ERI", label = "Eritrea"),
    Country(id = "EST", label = "Estonia"),
    Country(id = "ETH", label = "Ethiopia"),
    Country(id = "FLK", label = "Falkland Islands (Malvinas)"),
    Country(id = "FRO", label = "Faroe Islands"),
    Country(id = "FJI", label = "Fiji"),
    Country(id = "FIN", label = "Finland"),
    Country(id = "FRA", label = "France"),
    Country(id = "GUF", label = "French Guiana"),
    Country(id = "PYF", label = "French Polynesia"),
    Country(id = "ATF", label = "French Southern Territories"),
    Country(id = "GAB", label = "Gabon"),
    Country(id = "GMB", label = "Gambia"),
    Country(id = "GEO", label = "Georgia"),
    Country(id = "DEU", label = "Germany"),
    Country(id = "GHA", label = "Ghana"),
    Country(id = "GIB", label = "Gibraltar"),
    Country(id = "GRC", label = "Greece"),
    Country(id = "GRL", label = "Greenland"),
    Country(id = "GRD", label = "Grenada"),
    Country(id = "GLP", label = "Guadeloupe"),
    Country(id = "GUM", label = "Guam"),
    Country(id = "GTM", label = "Guatemala"),
    Country(id = "GGY", label = "Guernsey"),
    Country(id = "GIN", label = "Guinea"),
    Country(id = "GNB", label = "Guinea-Bissau"),
    Country(id = "GUY", label = "Guyana"),
    Country(id = "HTI", label = "Haiti"),
    Country(id = "HMD", label = "Heard Island and McDonald Islands"),
    Country(id = "VAT", label = "Holy See (Vatican City State)"),
    Country(id = "HND", label = "Honduras"),
    Country(id = "HUN", label = "Hungary"),
    Country(id = "ISL", label = "Iceland"),
    Country(id = "IRN", label = "Iran (The Islamic Republic of)"),
    Country(id = "IRQ", label = "Iraq"),
    Country(id = "IRL", label = "Ireland"),
    Country(id = "IMN", label = "Isle of Man"),
    Country(id = "ISR", label = "Israel"),
    Country(id = "ITA", label = "Italy"),
    Country(id = "JAM", label = "Jamaica"),
    Country(id = "JEY", label = "Jersey"),
    Country(id = "JOR", label = "Jordan"),
    Country(id = "KAZ", label = "Kazakhstan"),
    Country(id = "KEN", label = "Kenya"),
    Country(id = "KIR", label = "Kiribati"),
    Country(id = "PRK", label = "North Korea"),
    Country(id = "KOR", label = "South Korea"),
    Country(id = "KWT", label = "Kuwait"),
    Country(id = "KGZ", label = "Kyrgyzstan"),
    Country(id = "LAO", label = "Laos"),
    Country(id = "LVA", label = "Latvia"),
    Country(id = "LBN", label = "Lebanon"),
    Country(id = "LSO", label = "Lesotho"),
    Country(id = "LBR", label = "Liberia"),
    Country(id = "LBY", label = "Libyan Arab Jamahiriya"),
    Country(id = "LIE", label = "Liechtenstein"),
    Country(id = "LTU", label = "Lithuania"),
    Country(id = "LUX", label = "Luxembourg"),
    Country(id = "MAC", label = "Macao"),
    Country(id = "MKD", label = "Macedonia (The former Yugoslav Republic)"),
    Country(id = "MDG", label = "Madagascar"),
    Country(id = "MWI", label = "Malawi"),
    Country(id = "MDV", label = "Maldives"),
    Country(id = "MLI", label = "Mali"),
    Country(id = "MLT", label = "Malta"),
    Country(id = "MHL", label = "Marshall Islands"),
    Country(id = "MTQ", label = "Martinique"),
    Country(id = "MRT", label = "Mauritania"),
    Country(id = "MUS", label = "Mauritius"),
    Country(id = "MYT", label = "Mayotte"),
    Country(id = "MEX", label = "Mexico"),
    Country(id = "FSM", label = "Micronesia (The Federated States of)"),
    Country(id = "MDA", label = "Moldova (The Republic of)"),
    Country(id = "MCO", label = "Monaco"),
    Country(id = "MNG", label = "Mongolia"),
    Country(id = "MNE", label = "Montenegro"),
    Country(id = "MSR", label = "Montserrat"),
    Country(id = "MAR", label = "Morocco"),
    Country(id = "MOZ", label = "Mozambique"),
    Country(id = "MMR", label = "Myanmar"),
    Country(id = "NAM", label = "Namibia"),
    Country(id = "NRU", label = "Nauru"),
    Country(id = "NPL", label = "Nepal"),
    Country(id = "NLD", label = "Netherlands"),
    Country(id = "NCL", label = "New Caledonia"),
    Country(id = "NZL", label = "New Zealand"),
    Country(id = "NIC", label = "Nicaragua"),
    Country(id = "NER", label = "Niger"),
    Country(id = "NGA", label = "Nigeria"),
    Country(id = "NIU", label = "Niue"),
    Country(id = "NFK", label = "Norfolk Island"),
    Country(id = "MNP", label = "Northern Mariana Islands"),
    Country(id = "NOR", label = "Norway"),
    Country(id = "OMN", label = "Oman"),
    Country(id = "PAK", label = "Pakistan"),
    Country(id = "PLW", label = "Palau"),
    Country(id = "PSE", label = "Palestinian Territory (Occupied)"),
    Country(id = "PAN", label = "Panama"),
    Country(id = "PNG", label = "Papua New Guinea"),
    Country(id = "PRY", label = "Paraguay"),
    Country(id = "PER", label = "Peru"),
    Country(id = "PCN", label = "Pitcairn"),
    Country(id = "POL", label = "Poland"),
    Country(id = "PRT", label = "Portugal"),
    Country(id = "PRI", label = "Puerto Rico"),
    Country(id = "QAT", label = "Qatar"),
    Country(id = "REU", label = "Reunion"),
    Country(id = "ROU", label = "Romania"),
    Country(id = "RUS", label = "Russian Federation"),
    Country(id = "RWA", label = "Rwanda"),
    Country(id = "BLM", label = "Saint Barthelemy"),
    Country(id = "SHN", label = "Saint Helena (Ascension and Tristan da Cunha)"),
    Country(id = "KNA", label = "Saint Kitts and Nevis"),
    Country(id = "LCA", label = "Saint Lucia"),
    Country(id = "MAF", label = "Saint Martin (French)"),
    Country(id = "SPM", label = "Saint Pierre and Miquelon"),
    Country(id = "VCT", label = "Saint Vincent and the Grenadines"),
    Country(id = "WSM", label = "Samoa"),
    Country(id = "SMR", label = "San Marino"),
    Country(id = "STP", label = "Sao Tome and Principe"),
    Country(id = "SAU", label = "Saudi Arabia"),
    Country(id = "SEN", label = "Senegal"),
    Country(id = "SRB", label = "Serbia"),
    Country(id = "SYC", label = "Seychelles"),
    Country(id = "SLE", label = "Sierra Leone"),
    Country(id = "SXM", label = "Sint Maarten (Dutch)"),
    Country(id = "SVK", label = "Slovakia"),
    Country(id = "SVN", label = "Slovenia"),
    Country(id = "SLB", label = "Solomon Islands"),
    Country(id = "SOM", label = "Somalia"),
    Country(id = "ZAF", label = "South Africa"),
    Country(id = "SGS", label = "South Georgia and the South Sandwich Islands"),
    Country(id = "SSD", label = "South Sudan"),
    Country(id = "ESP", label = "Spain"),
    Country(id = "LKA", label = "Sri Lanka"),
    Country(id = "SDN", label = "Sudan"),
    Country(id = "SUR", label = "Suriname"),
    Country(id = "SJM", label = "Svalbard and Jan Mayen"),
    Country(id = "SWZ", label = "Swaziland"),
    Country(id = "SWE", label = "Sweden"),
    Country(id = "CHE", label = "Switzerland"),
    Country(id = "SYR", label = "Syrian Arab Republic"),
    Country(id = "TWN", label = "Taiwan"),
    Country(id = "TJK", label = "Tajikistan"),
    Country(id = "TZA", label = "Tanzania (The United Republic of)"),
    Country(id = "THA", label = "Thailand"),
    Country(id = "TLS", label = "Timor-Leste"),
    Country(id = "TGO", label = "Togo"),
    Country(id = "TKL", label = "Tokelau"),
    Country(id = "TON", label = "Tonga"),
    Country(id = "TTO", label = "Trinidad and Tobago"),
    Country(id = "TUN", label = "Tunisia"),
    Country(id = "TUR", label = "Turkey"),
    Country(id = "TKM", label = "Turkmenistan"),
    Country(id = "TCA", label = "Turks and Caicos Islands"),
    Country(id = "TUV", label = "Tuvalu"),
    Country(id = "UGA", label = "Uganda"),
    Country(id = "UKR", label = "Ukraine"),
    Country(id = "ARE", label = "United Arab Emirates"),
    Country(id = "GBR", label = "United Kingdom"),
    Country(id = "USA", label = "United States"),
    Country(id = "UMI", label = "United States Minor Outlying Islands"),
    Country(id = "URY", label = "Uruguay"),
    Country(id = "UZB", label = "Uzbekistan"),
    Country(id = "VUT", label = "Vanuatu"),
    Country(id = "VEN", label = "Venezuela (The Bolivarian Republic of)"),
    Country(id = "VGB", label = "Virgin Islands (British)"),
    Country(id = "VIR", label = "Virgin Islands (U.S.)"),
    Country(id = "WLF", label = "Wallis and Futuna"),
    Country(id = "ESH", label = "Western Sahara"),
    Country(id = "YEM", label = "Yemen"),
    Country(id = "ZMB", label = "Zambia"),
    Country(id = "ZWE", label = "Zimbabwe"),
    Country(id = "ALA", label = "Aland Islands")
  )
}
